language: node_js
if: tag IS blank
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      name: "lint"
      script: npm run lint
    - name: "coverage"
      script: npm run coverage
      after_script: bash <(curl -s https://codecov.io/bash)
    - stage: release
      name: "semantic release"
      before_script: npm run build
      script: cd ./build && npx semantic-release
