language: node_js
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script: npm run test:codestyle
    - script: npm run test:coverage
      after_script: bash <(curl -s https://codecov.io/bash)
    - stage: release
      script: npm run release
