language: node_js
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      name: "lint"
      script: npm run lint
    - name: "coverage"
      script: npm run coverage
      after_script: bash <(curl -s https://codecov.io/bash)
    - stage: release
      deploy:
          provider: script
          skip_cleanup: true
          script:
            - npx semantic-release
