on: push
runs-on: ubuntu-latest
env:
  CI: true
jobs:
  install:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci 
  coverage:
    needs: install
    steps:
    - run: npm run coverage
  lint:
    needs: install
    steps:
    - run: npm run lint
