on: push
env:
  CI: true
defaults:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1
    with:
      node-version: '12.x'
  - run: npm ci
jobs:
  coverage:
    steps:
    - run: npm run coverage
  lint:
    steps:
    - run: npm run lint
